kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ template "registrydocker.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  annotations: 
    "helm.sh/hook": pre-install
  labels:
    app: {{ template "registrydocker.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.volumes.server }}
    path:   {{ .Values.volumes.path }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  #persistentVolumeReclaimPolicy: Recycle