apiVersion: v1
kind: Service
metadata:
  name: {{ include "registrydocker.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "registrydocker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "registrydocker.selectorLabels" . | nindent 4 }}
