- name: check if config file exist
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file


- name: check if gitlab already installed
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file


- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_install_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
  when: not gitlab_file.stat.exists

- name: install repo
  command: bash /tmp/gitlab_install_repository.sh
  when: not gitlab_file.stat.exists

- name: install gitlab
  package:
    name: "{{ gitlab_package }}"
    state: present
  when: not gitlab_file.stat.exists

- name: inject gitlab.rb template
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: "0600"
  notify:
    - Run gitlab-ctl reconfigure
  when:
    - gitlab_configuration_file is not defined