
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "diskinflux.fullname" . }}
  labels:
    {{- include "diskinflux.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "diskinflux.fullname" . }}
  capacity:
    storage: {{ .Values.pv.capacity.storage }}
  accessModes:
  - ReadWriteOnce
  nfs:
    server: {{ .Values.volumes.server }}
    path:   {{ .Values.volumes.path }}